### ISSUE TITLE
Open Weekly Note unable to create new file

### ISSUE THREAD

**Issue by SpektacleFR** [liamcain/obsidian-periodic-notes#194]
The issue I'm having here is pretty bizarre.  So I downloaded the plugin yesterday (Aug 8 2023, 32nd week of August) and ran the "Open Weekly Note" command.  All goes well, except that it created a note for week 31 (one week behind).  Upon attempting to open that already-created note, I get the following error: "Unable to create new note"

I checked that I had my name template proper in the config files, and that is proper.  My format is as such:
`[W]W YYYY`
The little indicator helper to the left states "W23 2023" - the proper date.

I'm not exactly sure why this happens, but it sure is annoying, having to manually open my weeklies that are one week behind.

In the JS Developer Console, I get the following error:
```js
failed to create file: 'Weekly/W31 2023.md' Error: File already exists.
    at t.<anonymous> (app.js:1:1023347)
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
createWeeklyNote @ plugin:periodic-notes:387
```
But this is the only output that I've been given.

**Comment by mossadacity** [comment]
Likely duplicate of #185 - am experiencing this as well, see comments there.
